name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - "backend/server.js"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-{https://wert-effh.onrender.com}?key={https://wert-effh.onrender.com}"
